# Configuration for ConfigLoader (ImageLoader)
# ImageLoader의 기본 섹션 및 정책을 정의합니다.

config_loader:
  yaml:
    source_paths:
      - path: "./image.yaml"
        section: "image"  # ImageLoader가 사용할 섹션
    enable_env: false  # ${} 패턴 충돌 방지
    enable_include: true
    enable_placeholder: false  # PlaceholderResolver 비활성화
    enable_reference: true  # ConfigNormalizer에서 처리
    safe_mode: true
    encoding: "utf-8"
    on_error: "ignore"
    sort_keys: false
    default_flow_style: false
    indent: 2
  
  # Normalizer options
  drop_blanks: true
  resolve_reference: true
  
  # Merge options
  merge_order: "base→yaml→arg"
  merge_mode: "deep"
