# ========================================
# Production Logging Configuration
# ========================================
# 프로덕션 환경용 - 파일만 사용, 엄격한 정책

name: "production"

sinks:
  # 일반 로그 (INFO 이상)
  - sink_type: "file"
    filepath: "output/logs/production/{time:YYYY-MM-DD}_app.log"
    level: "INFO"
    rotation: "100 MB"
    retention: "30 days"
    compression: "zip"
    format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level:<8} | {process} | {thread} | {name} | {file}:{line} | {message}"
    enqueue: true
    serialize: false
    backtrace: true
    diagnose: false
    colorize: false
    catch: true
    
  # 에러 로그 (ERROR 이상)
  - sink_type: "file"
    filepath: "output/logs/production/errors/{time:YYYY-MM-DD}_error.log"
    level: "ERROR"
    rotation: "50 MB"
    retention: "90 days"
    compression: "zip"
    format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level:<8} | {process} | {thread} | {name} | {file}:{line} | {function} | {message}"
    enqueue: true
    serialize: false
    backtrace: true
    diagnose: true
    colorize: false
    catch: true
