# ========================================
# Time-based Rotation Configuration
# ========================================
# 시간 기준 로그 회전 예제

name: "time_rotation"

sinks:
  # 일별 로그 회전 (매일 0시)
  - sink_type: "file"
    filepath: "output/logs/daily/{time:YYYY-MM-DD}_app.log"
    level: "INFO"
    rotation: "00:00"  # 매일 자정
    retention: "30 days"
    compression: "zip"
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {message}"
    enqueue: true
    
  # 주별 로그 회전
  - sink_type: "file"
    filepath: "output/logs/weekly/{time:YYYY-WW}_weekly.log"
    level: "WARNING"  # 경고 이상만
    rotation: "1 week"  # 매주 회전
    retention: "12 weeks"
    compression: "tar.gz"
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {message}"
    enqueue: true
    
  # 콘솔
  - sink_type: "console"
    level: "INFO"
    format: "<green>{time:HH:mm:ss}</green> | <level>{message}</level>"
    colorize: true
