# ============================================================
# 테스트용 설정 파일
# ============================================================
image:
  max_width: 2048
  max_height: 1536
  format: "PNG"
  quality: 100

ocr:
  lang: "kor+eng"
  psm: 6
  oem: 3
  
database:
  host: "localhost"
  port: 5432
  name: "cashop"
