# ========================================
# Logging Configuration (Full Variables)
# ========================================
# 📁 로그 기본 저장 디렉터리
dir_name: "logs/crawl"

# 📦 로그 파일 회전 정책
# - 파일 크기 기준: "10 MB"
# - 시간 기준: "00:00" (매일 0시 회전)
# - 주기 기준: "1 week"
rotation: "10 MB"

# 🕒 로그 보관 정책
# - "7 days": 7일 지난 로그 자동 삭제
# - "1 month": 1개월 보관
retention: "7 days"

# 🧱 로그 레벨 (DEBUG / INFO / WARNING / ERROR / CRITICAL)
level: "INFO"

# 🧾 로그 포맷
# 사용 가능한 필드:
#   {time}, {level}, {name}, {message}, {file}, {line}, {function}, {process}, {thread}
format: "[{time:YYYY-MM-DD HH:mm:ss}] | {level:<8} | {name:<15} | {message}"

# ===============================
# SINK (로그 출력 대상) 정의
# ===============================
# 여러 Sink를 병렬로 등록할 수 있음 (예: 파일 + 콘솔 + 압축 로그)
sink:
  # ────────────────
  # 1️⃣ 파일 로그 Sink
  # ────────────────
  - file: "logs/crawl/{time:YYYY-MM-DD}_crawl.log"   # 파일 경로 템플릿
    console: false                                   # 콘솔 출력 여부 (이 sink에서는 비활성화)
    rotation: "10 MB"                                # 개별 sink 회전 정책
    retention: "7 days"                              # 개별 sink 보관 정책
    compression: "zip"                               # 로그 파일 압축 방식 (zip, tar, gz 등)
    enqueue: true                                    # 비동기 안전 모드
    backtrace: true                                  # 예외 발생 시 전체 스택 추적 출력
    diagnose: false                                  # 코드 분석 정보 출력 여부
    colorize: false                                  # 색상 출력 비활성화 (콘솔 전용)
    delay: false                                     # 파일 생성 지연 여부
    catch: true                                      # 예외 발생 시 내부에서 처리

  # ────────────────
  # 2️⃣ 콘솔 Sink
  # ────────────────
  - console: true                                    # 콘솔 활성화
    file: null                                       # 콘솔 Sink는 파일 경로 없음
    colorize: true                                   # ANSI 색상 사용 (loguru 지원)
    enqueue: false                                   # 콘솔 출력은 비동기 큐 사용 안 함
    backtrace: false                                 # 콘솔엔 스택 트레이스 생략
    diagnose: false                                  # 콘솔에 코드 상세정보 생략
    level: "DEBUG"                                   # 이 Sink에만 다른 레벨 적용 가능 (선택)
    format: "<green>{time:HH:mm:ss}</green> | <level>{message}</level>"

  # ────────────────
  # 3️⃣ 에러 전용 파일 Sink (선택적)
  # ────────────────
  - file: "logs/crawl/errors/{time:YYYY-MM-DD}_error.log"
    console: false
    level: "ERROR"                                   # 특정 레벨 이상만 기록
    rotation: "50 MB"
    retention: "30 days"
    compression: "zip"
    enqueue: true
    backtrace: true
    diagnose: true
