# -*- coding: utf-8 -*-
# Taobao 크롤링용 Firefox 설정 (자동화 탐지 회피)

firefox:
  provider: "firefox"
  headless: false                # GUI 모드 (탐지 회피)
  window_size: [1440, 900]       # 일반 해상도
  
  # -------------------------------------------------------------------------
  # Session 관리 (중요!)
  # -------------------------------------------------------------------------
  session_path: "data/session/firefox_taobao.json"
  save_session: true             # 세션 자동 저장/복원
  
  # -------------------------------------------------------------------------
  # User-Agent & Accept-Language (중국 사이트 최적화)
  # -------------------------------------------------------------------------
  # Firefox 120.0 Windows 기반
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
  
  # 중국어 우선 (한국어, 영어 포함)
  accept_languages: "zh-CN,zh;q=0.9,ko;q=0.8,en;q=0.7"
  
  # -------------------------------------------------------------------------
  # 자동화 탐지 회피 (Anti-Detection)
  # -------------------------------------------------------------------------
  disable_automation: true       # navigator.webdriver = false
  
  # Firefox 전용 preferences
  dom_enabled: false             # dom.webdriver.enabled = false
  resist_fingerprint_enabled: false  # 지문 방지 비활성화 (일반 브라우저처럼)
  
  # -------------------------------------------------------------------------
  # Firefox 경로 설정
  # -------------------------------------------------------------------------
  driver_path: null              # geckodriver 자동 다운로드
  binary_path: null              # Firefox 실행 파일 자동 감지
  profile_path: null             # 새 프로필 사용 (또는 기존 프로필 경로)
  
  # -------------------------------------------------------------------------
  # Driver 관리
  # -------------------------------------------------------------------------
  use_webdriver_manager: true    # geckodriver 자동 다운로드/업데이트
  
  # -------------------------------------------------------------------------
  # 추가 옵션
  # -------------------------------------------------------------------------
  # 쿠키/캐시 활성화 (일반 브라우저처럼)
  enable_cookies: true
  enable_cache: true
  
  # 이미지 로딩 (false면 속도 향상, 탐지 위험 증가)
  load_images: true
  
  # JavaScript 활성화 (필수)
  enable_javascript: true
  
  # -------------------------------------------------------------------------
  # 로깅
  # -------------------------------------------------------------------------
  log_config: "logs/firefox_taobao.log"
