# Configuration for ConfigLoader (crawl_utils - Crawl)
# Crawl 서비스의 기본 섹션 및 정책을 정의합니다.

config_policy:
  yaml_policy:
    file_path: null
    default_section: "crawl"  # Crawl default section
    enable_env: false
    enable_include: false
    enable_placeholder: false
    enable_reference: false
    safe_mode: true
    encoding: "utf-8"
    on_error: "ignore"
    sort_keys: false
    default_flow_style: false
    indent: 2
  
  # Normalizer options
  drop_blanks: true
  resolve_reference: true
  
  # Merge options
  merge_order: "base→yaml→arg"
  merge_mode: "deep"
