# ============================================================================
# Default Crawl Configuration
# ============================================================================
# 기본 크롤링 설정입니다. 실제 사용시 이 파일을 복사하여 수정하세요.
# 
# 예제:
#   - crawl_simple.yaml: 간단한 설정 예제
#   - crawl_full.yaml: 모든 옵션을 포함한 전체 예제
# 
# 사용법:
#   from crawl_utils import run_sync_crawl, FirefoxWebDriver
#   
#   with FirefoxWebDriver(config) as driver:
#       items = run_sync_crawl("crawl_utils/config/crawl.yaml", driver)
# ============================================================================

crawl:
  navigation:
    base_url: "https://example.com"
    start_page: 1
    max_pages: 1
  
  storage:
    image:
      base_dir: "output/crawl/images"
  
  execution_mode: "sync"
