# ========================================
# Firefox WebDriver Configuration
# ========================================

# Provider type
provider: "firefox"

# Basic settings
headless: false
window_size: [1440, 900]

# Session management
session_path: null
save_session: false

# Driver path (null = auto-detect)
driver_path: null

# Browser options
user_agent: null
accept_languages: "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7"

# Automation detection bypass
disable_automation: true

# Logging configuration
# - YAML path: "config/webdriver_log.yaml"
# - dict: {"name": "firefox", "sinks": [...]}
# - null: default console logging
log_config: "crawl_utils/config/webdriver_log.yaml"

# Firefox-specific settings
binary_path: null
profile_path: null
dom_enabled: false
resist_fingerprint_enabled: false
use_webdriver_manager: true
