# ============================================================
# ConfigLoaderPolicy
# ============================================================
source:

  - src: ["M:/CALife/CAShop - 구매대행/_code/modules/crawl_utils/configs/webdriver.yaml", "webdriver"]
    yaml_parser:
      safe_mode: true
      encoding: "utf-8"
      enable_env: true              # ✅ 환경변수 resolving 활성화
      enable_include: true
      enable_placeholder: true
      enable_reference: true
    
    yaml_normalizer:
      normalize_keys: true
      drop_blanks: true
      resolve_vars: true
    
    yaml_merge:
      deep: true
      overwrite: true

  - src: ["M:/CALife/CAShop - 구매대행/_code/modules/crawl_utils/configs/webdriver_china.yaml", "webdriver_china"]
    yaml_parser:
      safe_mode: true
      encoding: "utf-8"
      enable_env: true              # ✅ 환경변수 resolving 활성화
      enable_include: true
      enable_placeholder: true
      enable_reference: true
    
    yaml_normalizer:
      normalize_keys: true
      drop_blanks: true
      resolve_vars: true
    
    yaml_merge:
      deep: true
      overwrite: true

  - src: ["M:/CALife/CAShop - 구매대행/_code/modules/crawl_utils/configs/webdriver_global.yaml", "webdriver_global"]
    yaml_parser:
      safe_mode: true
      encoding: "utf-8"
      enable_env: true              # ✅ 환경변수 resolving 활성화
      enable_include: true
      enable_placeholder: true
      enable_reference: true
    
    yaml_normalizer:
      normalize_keys: true
      drop_blanks: true
      resolve_vars: true
    
    yaml_merge:
      deep: true
      overwrite: true

log:
  enabled: true
  name: "webdriver_config_loader"
  level: "INFO"
  sinks:
    - sink_type: "file"
      file_path: "M:/CALife/CAShop - 구매대행/_code/logs/webdriver_firefox/_{time:YYYY-MM-DD}.log"
      level: "INFO"
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
      rotation: Optional[Union[str, int]] = "10 MB"
      retention: Optional[Union[str, int]] = "7 days"
      compression: Optional[str] = None
      enqueue: bool = True
      serialize: bool = False
      backtrace: bool = True
      diagnose: bool = True
      colorize: bool = True
      catch: bool = True
  context: {}

# BaseModel 정책
# base_model_normalizer:
#   normalize_keys: true
#   drop_blanks: false
#   resolve_vars: false

# base_model_merge:
#   deep: false
#   overwrite: false

# # Dict 정책
# dict_normalizer:
#   normalize_keys: true
#   drop_blanks: true
#   resolve_vars: false

# dict_merge:
#   deep: false
#   overwrite: true