# Configuration for ConfigLoader (OTO Pipeline)
# OTO 파이프라인의 모든 모듈 정책을 통합 관리

config_loader:
  yaml:
    source_paths:
      - path: "${configs_dir}/paths.local.yaml"
      - path: "${configs_dir}/oto/image.yaml"
      - path: "${configs_dir}/oto/ocr.yaml"
      - path: "${configs_dir}/oto/overlay.yaml"
      - path: "${configs_dir}/oto/translate.yaml"

    enable_env: false  # ${} 패턴이 환경 변수로 오해되는 것 방지
    enable_include: true
    enable_placeholder: false  # PlaceholderResolver가 ${} reference를 침범하지 않도록
    enable_reference: true  # ConfigNormalizer에서 처리 (context 필요)
    safe_mode: true
    encoding: "utf-8"
    on_error: "ignore"
    sort_keys: false
    default_flow_style: false
    indent: 2
  
  # Normalizer options
  drop_blanks: true
  resolve_reference: true
  
  # Merge options
  merge_order: "base→yaml→arg"
  merge_mode: "deep"
