# Configuration for ConfigLoader (OTO Pipeline)
# OTO 파이프라인의 모든 모듈 정책을 통합 관리

config_loader:
  yaml:
    source_paths:
      - path: "{{configs_dir}}/oto/image.yaml"
        section: "image"  # ImageLoader가 사용할 섹션
      - path: "{{configs_dir}}/oto/ocr.yaml"
        section: "ocr"  # ImageOCR가 사용할 섹션
      - path: "{{configs_dir}}/oto/overlay.yaml"
        section: "overlay"  # ImageOverlay가 사용할 섹션
      - path: "{{configs_dir}}/oto/translate.yaml"
        section: "translate"  # Translator가 사용할 섹션
    
    enable_env: true
    enable_include: false
    enable_placeholder: true
    enable_reference: true
    safe_mode: true
    encoding: "utf-8"
    on_error: "ignore"
    sort_keys: false
    default_flow_style: false
    indent: 2
  
  # Normalizer options
  drop_blanks: true
  resolve_reference: true
  
  # Merge options
  merge_order: "base→yaml→arg"
  merge_mode: "deep"
