# ============================================================================
# ImageOverlay - OTO Configuration
# ============================================================================
# OTO 파이프라인에서 사용하는 ImageOverlay 설정
# 필수 항목만 활성화, 고급 옵션은 주석 처리

overlay:
  # --------------------------------------------------------------------------
  # 1. Source - 소스 이미지 설정 (런타임에서 Image 객체 전달)
  # --------------------------------------------------------------------------
  source:
    path: "{{temp_input_dir}}/01.jpg"              # 기본값 (런타임 오버라이드)
    # must_exist: false
    # convert_mode: "RGB"
  
  # --------------------------------------------------------------------------
  # 2. Items - 텍스트 오버레이 목록 (런타임에서 OverlayItem 전달)
  # --------------------------------------------------------------------------
  items:
    - text: "TEST0 한글테스트"          # 예제 (런타임에서 교체됨)
      polygon:
        - [100, 100]
        - [400, 100]
        - [400, 200]
        - [100, 200]
      font:
        font_dir: "{{fonts_dir}}"
        family: "HMKMMAG.TTF"           # 한글 폰트
        size: 48                        # 크기 명시
        fill: "#FF0000"                 # 빨간색 (눈에 잘 띄게)
        stroke_fill: "#000000"          # 검은색 외곽선
        stroke_width: 3                 # 굵은 외곽선
    
    - text: "TEST1 English"          # 예제 (런타임에서 교체됨)
      polygon:
        - [150, 300]
        - [500, 300]
        - [500, 400]
        - [150, 400]
      font:
        font_dir: "{{fonts_dir}}"
        family: "HMKMMAG.TTF"
        size: 60
        fill: "#0000FF"                 # 파란색
        stroke_fill: "#FFFFFF"          # 흰색 외곽선
        stroke_width: 4
    
    - text: "TEST2 マルコ"          # 예제 (런타임에서 교체됨)
      polygon:
        - [200, 500]
        - [600, 500]
        - [600, 600]
        - [200, 600]
      font:
        font_dir: "{{fonts_dir}}"
        family: "HMKMMAG.TTF"           # 폰트 패밀리
        size: 72                        # 더 큰 크기
        fill: "#00FF00"                 # 초록색
        stroke_fill: "#000000"          # 검은색 외곽선
        stroke_width: 5                 # 더 굵은 외곽선
      
      # 텍스트 배치 설정
      # anchor: "mm"
      # offset: [0.0, 0.0]
      # max_width_ratio: 0.95
  
  # --------------------------------------------------------------------------
  # 3. Background Opacity - 배경 투명도
  # --------------------------------------------------------------------------
  background_opacity: 0.0
  
  # --------------------------------------------------------------------------
  # 4. Save - 이미지 저장 설정
  # --------------------------------------------------------------------------
  save:
    save_copy: true                    # 오버레이된 이미지 저장 (임시로 비활성화)
    directory: "{{temp_input_dir}}"      # 저장 디렉토리
    
    name:
      # as_type: "file"
      # prefix: null
      # name: ""
      suffix: "overlay"
      # tail: null
      # extension: null
      # delimiter: "_"
      tail_mode: "counter"
      # date_format: "%Y-%m-%d"
      # counter_width: 3
      # auto_expand: true
      # tail_suffix: null
      # sanitize: true
      # case: "keep"
      ensure_unique: false
    
    # ops:
    #   as_type: "file"
    #   exist:
    #     must_exist: false
    #     create_if_missing: true
    #     overwrite: false
    #   ext:
    #     require_ext: false
    #     default_ext: null
    #     allowed_exts: null
    
    # format: null
    quality: 95
  
  # --------------------------------------------------------------------------
  # 5. Meta - 메타데이터 저장 설정
  # --------------------------------------------------------------------------
  meta:
    save_meta: true                     # 메타 저장 활성화
    directory: "{{temp_input_dir}}"      # 메타 저장 디렉토리
    
    name:
    #   as_type: "file"
    #   prefix: null
      # name: ""
      suffix: "overlay_meta"
    #   tail: null
    #   extension: ".json"
    #   delimiter: "_"
      tail_mode: "counter"
    #   date_format: "%Y-%m-%d"
    #   counter_width: 3
    #   auto_expand: true
    #   tail_suffix: null
    #   sanitize: true
    #   case: "keep"
      ensure_unique: false
    # ops:
    #   as_type: "file"
    #   exist:
    #     must_exist: false
    #     create_if_missing: true
    #     overwrite: true
    #   ext:
    #     require_ext: false
    #     default_ext: ".json"
    #     allowed_exts: null
  
  # --------------------------------------------------------------------------
  # 6. Log - 로그 설정
  # --------------------------------------------------------------------------
  log:
    name: "image_overlay"               # 서비스 이름 (필수)
    level: "INFO"                       # 로그 레벨
    # format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"
    # colorize: true
    # serialize: false
    # backtrace: false
    # diagnose: false
    # enqueue: false
    # catch: true
    
    handlers:
      - sink: "output/logs/image_overlay_{time:YYYY-MM-DD}.log"
        # level: "DEBUG"
        # format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {message}"
        rotation: "1 day"
        retention: "7 days"
        # compression: "zip"
        # encoding: "utf-8"
        # colorize: false
        # serialize: false
        # backtrace: true
        # diagnose: false
        # enqueue: false
        # catch: true
