# ============================================================================
# ImageOverlay - OTO Configuration
# ============================================================================
# OTO 파이프라인에서 사용하는 ImageOverlay 설정
# 필수 항목만 활성화, 고급 옵션은 주석 처리

overlay:
  # --------------------------------------------------------------------------
  # 1. Source - 소스 이미지 설정 (런타임에서 Image 객체 전달)
  # --------------------------------------------------------------------------
  source:
    path: ""              # 기본값 (런타임 오버라이드)
    # must_exist: false
    # convert_mode: "RGB"
  
  # --------------------------------------------------------------------------
  # 2. Texts - 텍스트 오버레이 목록 (런타임에서 OverlayItem 전달)
  # --------------------------------------------------------------------------
  texts:
    - text: "Sample"                    # 예제 (런타임에서 교체됨)
      polygon:
        - [10, 10]
        - [200, 10]
        - [200, 50]
        - [10, 50]
      
      # 폰트 설정
      font:
        family: "NanumGothic"           # 폰트 패밀리
        size: 24                        # 폰트 크기
        fill: "#FFFFFF"                 # 텍스트 색상
        stroke_fill: "#000000"          # 외곽선 색상
        stroke_width: 2                 # 외곽선 두께
      
      # 텍스트 배치 설정
      # anchor: "mm"
      # offset: [0.0, 0.0]
      # max_width_ratio: 0.95
  
  # --------------------------------------------------------------------------
  # 3. Background Opacity - 배경 투명도
  # --------------------------------------------------------------------------
  # background_opacity: 0.0
  
  # --------------------------------------------------------------------------
  # 4. Save - 이미지 저장 설정
  # --------------------------------------------------------------------------
  save:
    save_copy: true                    # 오버레이된 이미지 저장 (임시로 비활성화)
    directory: "${temp_input_dir}"      # 저장 디렉토리
    
    name:
      # as_type: "file"
      # prefix: null
      # name: ""
      suffix: "_overlay"
      # tail: null
      # extension: null
      # delimiter: "_"
      # tail_mode: "counter"
      # date_format: "%Y-%m-%d"
      # counter_width: 3
      # auto_expand: true
      # tail_suffix: null
      # sanitize: true
      # case: "keep"
      # ensure_unique: true
    
    # ops:
    #   as_type: "file"
    #   exist:
    #     must_exist: false
    #     create_if_missing: true
    #     overwrite: false
    #   ext:
    #     require_ext: false
    #     default_ext: null
    #     allowed_exts: null
    
    # format: null
    quality: 95
  
  # --------------------------------------------------------------------------
  # 5. Meta - 메타데이터 저장 설정
  # --------------------------------------------------------------------------
  meta:
    save_meta: true                     # 메타 저장 활성화
    directory: "${temp_input_dir}"      # 메타 저장 디렉토리
    name:
    #   as_type: "file"
    #   prefix: null
    #   name: ""
      suffix: "_overlay"
    #   tail: null
    #   extension: ".json"
    #   delimiter: "_"
    #   tail_mode: null
    #   date_format: "%Y-%m-%d"
    #   counter_width: 3
    #   auto_expand: true
    #   tail_suffix: null
    #   sanitize: true
    #   case: "keep"
    #   ensure_unique: false
    # ops:
    #   as_type: "file"
    #   exist:
    #     must_exist: false
    #     create_if_missing: true
    #     overwrite: true
    #   ext:
    #     require_ext: false
    #     default_ext: ".json"
    #     allowed_exts: null
  
  # --------------------------------------------------------------------------
  # 6. Log - 로그 설정
  # --------------------------------------------------------------------------
  log:
    name: "image_overlay"               # 서비스 이름 (필수)
    level: "INFO"                       # 로그 레벨
    # format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"
    # colorize: true
    # serialize: false
    # backtrace: false
    # diagnose: false
    # enqueue: false
    # catch: true
    
    handlers:
      - sink: "output/logs/image_overlay_{time:YYYY-MM-DD}.log"
        # level: "DEBUG"
        # format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {message}"
        rotation: "1 day"
        retention: "7 days"
        # compression: "zip"
        # encoding: "utf-8"
        # colorize: false
        # serialize: false
        # backtrace: true
        # diagnose: false
        # enqueue: false
        # catch: true
