  # -------------------------------------------------------------------------
  # Firefox WebDriver 설정
  # -------------------------------------------------------------------------
  firefox:
    provider: "firefox"
    headless: false                # GUI 모드 (디버깅 시 true로 변경)
    window_size: [1440, 900]       # 브라우저 창 크기
    
    # Session 관리
    session_path: "data/session/firefox_xlcrawl.json"
    save_session: true             # 세션 저장/복원
    
    # Driver 경로 (자동 다운로드 사용 시 null)
    driver_path: null
    
    # User-Agent 설정
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
    accept_languages: "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7"
    
    # Automation 감지 우회
    disable_automation: true
    
    # Firefox 전용 경로
    binary_path: null              # Firefox 실행 파일 경로 (자동 감지 시 null)
    profile_path: null             # Firefox 프로필 디렉토리 (새 프로필 사용 시 null)
    
    # Firefox 전용 preferences
    dom_enabled: false             # dom.webdriver.enabled
    resist_fingerprint_enabled: false  # privacy.resistFingerprinting
    
    # geckodriver 관리
    use_webdriver_manager: true    # geckodriver 자동 다운로드
    
    # 로깅 설정
    log_config: "logs/xlcrawl_firefox.log"