# ============================================================================
# ImageOverlay Configuration (3rd Entrypoint) - pillow_utils
# ============================================================================
# Complete YAML for overlaying text on images
# 
# Usage:
#   from pillow_utils import ImageOverlay
#   overlay = ImageOverlay("configs/overlay.yaml")
#   result_path = overlay.run()
#
# Section-based access (for unified config):
#   from modules.cfg_utils import ConfigLoader
#   overlay_config = ConfigLoader("configs/overlay.yaml").get_section("overlay")
# ============================================================================

overlay:
  # Source image configuration
  source:
    path: "M:/CALife/CAShop - 구매대행/_code/scripts/01.jpg"
    must_exist: true
    convert_mode: null

  # Output image configuration
  output:
    save_copy: true
    directory: "M:/CALife/CAShop - 구매대행/output/images"
    filename: null
    suffix: "_overlay"
    format: null
    quality: 95
    ensure_unique: true

  # Metadata configuration
  meta:
    save_meta: true
    directory: "M:/CALife/CAShop - 구매대행/output/images"
    filename: null

  # Default font configuration for all text overlays
  font:
    family: "M:/CALife/CAShop - 구매대행/_code/data/fonts/HMKMMAG.TTF"
    size: 24
    fill: "#FF0000"
    stroke_fill: "#FFFFFF"
    stroke_width: 2

  # Background opacity (0.0-1.0)
  background_opacity: 0.0

  # Text overlay specifications
  texts:
  - text: "샘플 텍스트 1"
    polygon:
      - [100, 100]
      - [400, 100]
      - [400, 150]
      - [100, 150]
    font:
      family: "M:/CALife/CAShop - 구매대행/_code/data/fonts/HMKMMAG.TTF"
      size: 28
      fill: "#FF0000"
      stroke_fill: "#FFFFFF"
      stroke_width: 2
    anchor: "mm"
    offset: [0.0, 0.0]
    max_width_ratio: 0.95
    
  - text: "샘플 텍스트 2"
    polygon:
      - [100, 200]
      - [400, 200]
      - [400, 250]
      - [100, 250]
    font:
      family: "M:/CALife/CAShop - 구매대행/_code/data/fonts/NotoSansKR-Regular.ttf"
      size: 24
      fill: "#0000FF"
      stroke_fill: null
      stroke_width: 0
    anchor: "mm"
    offset: [0.0, 0.0]
    max_width_ratio: 0.95
