# ============================================================================
# ImageOverlay Configuration (No Section Version)
# ============================================================================
# This file works without an 'overlay:' section
# ConfigLoader will use root data directly

# Source image configuration
source:
  path: "M:/CALife/CAShop - 구매대행/_code/scripts/01.jpg"
  must_exist: true
  convert_mode: null

# Output image configuration
output:
  save_copy: true
  directory: "M:/CALife/CAShop - 구매대행/output/images"
  filename: null
  suffix: "_nosection_overlay"
  format: null
  quality: 95
  ensure_unique: true

# Metadata configuration
meta:
  save_meta: true
  directory: "M:/CALife/CAShop - 구매대행/output/images"
  filename: null

# Default font configuration
font:
  family: "M:/CALife/CAShop - 구매대행/_code/data/fonts/NotoSansKR-Regular.ttf"
  size: 24
  fill: "#FF0000"
  stroke_fill: "#FFFFFF"
  stroke_width: 2

# Background opacity
background_opacity: 0.0

# Text overlay specifications
texts:
  - text: "No Section Test"
    polygon:
      - [100, 100]
      - [400, 100]
      - [400, 150]
      - [100, 150]
    font:
      family: "M:/CALife/CAShop - 구매대행/_code/data/fonts/NotoSansKR-Regular.ttf"
      size: 28
      fill: "#00FF00"
      stroke_fill: null
      stroke_width: 0
    anchor: "mm"
    offset: [0.0, 0.0]
    max_width_ratio: 0.95
