# -*- coding: utf-8 -*-
# configs/paths.local.yaml

# -------------------------------------------------------------------------
# Base Paths
# -------------------------------------------------------------------------
root: "M:/CALife/CAShop - 구매대행"
base_path: "M:/CALife/CAShop - 구매대행/_code"

scripts_dir: "${base_path}/scripts"
modules_dir: "${base_path}/modules"
db_dir: "${base_path}/data/db"
fonts_dir: "${base_path}/data/fonts"

configs_dir: "${base_path}/configs"
configs_loader_dir: "${configs_dir}/loader"
configs_loader_file_oto: "${configs_loader_dir}/config_loader_oto.yaml"


temp_input_dir: "${base_path}/input"
temp_output_dir: "${base_path}/output/temp"
output_data_dir: "${root}/_data"
public_dir: "${root}/_public"