# -*- coding: utf-8 -*-
# configs/paths.local.yaml

# -------------------------------------------------------------------------
# Base Paths
# -------------------------------------------------------------------------
base_path: "M:/CALife/CAShop - 구매대행/_code"

root: "M:/CALife/CAShop - 구매대행"

code_dir: "${root}/_code"
scripts_dir: "${code_dir}/scripts"
modules_dir: "${code_dir}/modules"
db_dir: "${code_dir}/data/db"
fonts_dir: "${code_dir}/data/fonts"

configs_dir: "${code_dir}/configs"
configs_loader_dir: "${configs_dir}/loader"
configs_loader_file_path:
  configs_loader_oto: "${configs_loader_dir}/config_loader_oto.yaml"


temp_input_dir: "${base_path}/input"
temp_output_dir: "${base_path}/output/temp"
output_data_dir: "${root}/_data"
public_dir: "${root}/_public"