# -*- coding: utf-8 -*-
# configs/paths.local.yaml

# -------------------------------------------------------------------------
# Base Paths
# -------------------------------------------------------------------------
root: "M:/CALife/CAShop - 구매대행"
base_path: "M:/CALife/CAShop - 구매대행/_code"

data_dir: "{{base_path}}/data"
db_dir: "{{data_dir}}/db"
fonts_dir: "{{data_dir}}/fonts"
logs_dir: "{{base_path}}/logs"
configs_dir: "{{base_path}}/configs"

modules_dir: "{{base_path}}/modules"
scripts_dir: "{{base_path}}/scripts"

input_dir: "{{base_path}}/input"
output_dir: "{{base_path}}/output"

public_dir: "{{root}}/_public"

cashop_dir: "{{modules_dir}}/cashop"
cashop_configs_dir: "{{cashop_dir}}/configs"
cashop_base_config: "{{cashop_configs_dir}}/cashop_base.yaml"
cashop_xlcrawl_dir: "{{cashop_dir}}/xlcrawl" 
cashop_xlcrawl_configs_dir: "{{cashop_xlcrawl_dir}}/configs"  
cashop_xloto_dir: "{{cashop_dir}}/xloto"
cashop_xloto_configs_dir: "{{cashop_xloto_dir}}/configs"
cashop_test_dir: "{{cashop_dir}}/test"