# -*- coding: utf-8 -*-
# configs/paths.local.yaml

# -------------------------------------------------------------------------
# Base Paths
# -------------------------------------------------------------------------
root: "M:/CALife/CAShop - 구매대행"
base_path: "M:/CALife/CAShop - 구매대행/_code"

data_dir: "{{base_path}}/data"
db_dir: "{{data_dir}}/db"
fonts_dir: "{{data_dir}}/fonts"

modules_dir: "{{base_path}}/modules"
scripts_dir: "{{base_path}}/scripts"
logs_dir: "{{base_path}}/logs"
input_dir: "{{base_path}}/input"
output_dir: "{{base_path}}/output"

configs_dir: "{{base_path}}/configs"

configs_xloto_dir: "{{configs_dir}}/xloto"
configs_xlcrawl_dir: "{{configs_dir}}/xlcrawl"

public_dir: "{{root}}/_public"
configs_xloto_product_detail_base_dir: "{{public_dir}}/01.IMAGE"
configs_xlcrawl_product_detail_base_dir: "{{public_dir}}/01.IMAGE"

temp_input_dir: "{{input_dir}}/temp"
temp_output_dir: "{{output_dir}}/temp"

# Module configs
configs_crawl_dir: "{{modules_dir}}/crawl_utils/configs"
