# ============================================================================
# ImageLoader Configuration (1st Entrypoint) - pillow_utils
# ============================================================================
# Complete YAML for loading, processing, and saving images
# 
# Usage:
#   from pillow_utils import ImageLoader
#   loader = ImageLoader("configs/pillow.yaml")
#   result = loader.run()
#
# Section-based access (for unified config):
#   from modules.cfg_utils import ConfigLoader
#   loader_config = ConfigLoader("configs/pillow.yaml").get_section("pillow")
# ============================================================================

pillow:
  # Source image configuration
  source:
    path: "M:/CALife/CAShop - 구매대행/_code/scripts/01.jpg"
    must_exist: true
    convert_mode: null

  # Image save/copy configuration
  image:
    save_copy: true
    directory: "M:/CALife/CAShop - 구매대행/output/images"
    filename: null
    suffix: "_processed"
    format: null
    quality: 95
    ensure_unique: true

  # Metadata configuration
  meta:
    save_meta: true
    directory: "M:/CALife/CAShop - 구매대행/output/images"
    filename: null

  # Processing configuration
  processing:
    resize_to: null
    blur_radius: null
    convert_mode: null
