# -*- coding: utf-8 -*-
# configs/xlcrawl.yaml
# Excel 크롤링 자동화 설정

xlcrawl:
  # -------------------------------------------------------------------------
  # Download 컬럼 설정
  # -------------------------------------------------------------------------
  download_column: "download"  # Excel에서 download 컬럼 이름
  
  # -------------------------------------------------------------------------
  # 이미지 저장 설정
  # -------------------------------------------------------------------------
  image_save_dir: "output/images"  # 이미지 저장 디렉토리
  image_format: "jpg"              # 저장 형식
  image_quality: 95                # JPEG 품질 (1-100)
  

  
  # -------------------------------------------------------------------------
  # 크롤링 설정
  # -------------------------------------------------------------------------
  crawl:
    timeout: 30                    # 요청 타임아웃 (초)
    retry: 3                       # 재시도 횟수
    delay: 1                       # 요청 간 지연 (초)
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  
  # -------------------------------------------------------------------------
  # JS Extract 설정
  # -------------------------------------------------------------------------
  extract:
    # Extractor 타입 (js, dom, api)
    type: "js"
    
    # JavaScript snippet (페이지에서 실행)
    js_snippet: |
      return {
        title: document.querySelector('h1.product-title, h1[class*="title"], .item-title')?.innerText?.trim() || '',
        price: document.querySelector('.price, .product-price, [class*="price"]')?.innerText?.trim() || '',
        images: Array.from(document.querySelectorAll('img[class*="product"], img[class*="item"], .gallery img')).map(img => img.src || img.dataset.src).filter(Boolean),
        description: document.querySelector('.description, .product-description, [class*="desc"]')?.innerHTML || '',
        brand: document.querySelector('.brand, .product-brand')?.innerText?.trim() || '',
        category: document.querySelector('.category, .breadcrumb')?.innerText?.trim() || ''
      };
    
    # XPath 패턴 (DOM extractor용 - 백업)
    patterns:
      title: "//h1[@class='product-title']"
      price: "//span[@class='price']"
      images: "//img[@class='product-image']/@src"
      description: "//div[@class='description']"
    
    # 정규화 옵션
    normalize:
      strip_whitespace: true
      remove_html_tags: true
      fix_encoding: true
  
  # -------------------------------------------------------------------------
  # 로깅 설정
  # -------------------------------------------------------------------------
  logging:
    enabled: true
    log_file: "logs/xlcrawl.log"
    level: "INFO"
