# ============================================================================
# Translate - Translation Configuration
# ============================================================================
translate:
  # Provider 설정
  provider:
    provider: "deepl"
    source_lang: "ZH"
    target_lang: "KO"
    timeout: 30
  
  # Cache 설정 (중요: 인스턴스가 달라도 DB는 공유됨)
  store:
    save_db: true
    db_dir: "${db_dir}"
    db_name: "translate_cache.sqlite3"
    save_tr: false

# ============================================================================
# ImageLoader - Complete Configuration Example
# ============================================================================
# 모든 가능한 정책 옵션을 포함한 전체 예제입니다.
# 실제 사용시에는 필요한 항목만 선택하여 사용하세요.

image:
  # --------------------------------------------------------------------------
  # 1. Source - 소스 이미지 설정
  # --------------------------------------------------------------------------
  source:
    path: ""           # 소스 이미지 경로 (필수)
    must_exist: true                   # 파일 존재 여부 확인 (기본: false)
    convert_mode: "RGB"                 # PIL 모드 변환 (예: RGB, L, RGBA 등)
  
  # --------------------------------------------------------------------------
  # 2. Save - 이미지 저장 설정 (FSO 기반)
  # --------------------------------------------------------------------------
  save:
    save_copy: false                     # 이미지 복사본 저장 여부 (기본: true)
    directory: None       # 저장 디렉토리 (None이면 downloads 폴더)
  
  # --------------------------------------------------------------------------
  # 3. Meta - 메타데이터 저장 설정 (FSO 기반)
  # --------------------------------------------------------------------------
  meta:
    save_meta: true                     # 메타데이터 JSON 저장 여부
    directory: ""                     # 메타 디렉토리 (None이면 이미지와 동일)
    
    # FSO Name Policy - 메타데이터 파일명 정책
    name:
      as_type: "file"
      prefix: null
      name: ""                          # 소스 파일명 사용
      suffix: "_meta"                   # 메타 파일 접미사
      tail: null
      extension: ".json"                # 메타 파일 확장자
      delimiter: "_"
      tail_mode: null                   # counter 미사용
      date_format: "%Y-%m-%d"
      counter_width: 2
      auto_expand: true
      tail_suffix: null
      sanitize: true
      case: "keep"
      ensure_unique: false              # 메타는 덮어쓰기 허용
    
    # FSO Ops Policy
    ops:
      as_type: "file"
      exist:
        must_exist: false
        create_if_missing: true
        overwrite: true                 # 메타는 덮어쓰기
      ext:
        require_ext: false
        default_ext: ".json"
        allowed_exts: null
  
  # --------------------------------------------------------------------------
  # 4. Process - 이미지 처리 설정
  # --------------------------------------------------------------------------
  process:
    resize_to: null                     # 리사이즈 크기 [width, height]
    blur_radius: null                   # 블러 반경 (float)
    convert_mode: null                  # 처리 후 모드 변환
  
  # --------------------------------------------------------------------------
  # 5. Log - 로그 설정
  # --------------------------------------------------------------------------
  log:
    level: "INFO"                       # 로그 레벨: DEBUG|INFO|WARNING|ERROR
    format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"
    colorize: true                      # 컬러 출력
    serialize: false                    # JSON 직렬화
    backtrace: false                    # 백트레이스 포함
    diagnose: false                     # 진단 정보 포함
    enqueue: false                      # 비동기 큐 사용
    catch: true                         # 예외 캐치
    
    # 파일 출력 설정
    handlers:
      - sink: "${output_xloto_logs_dir}/image_loader_{time:YYYY-MM-DD}.log"
        level: "DEBUG"
        format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {message}"
        rotation: "1 day"               # 로테이션: 1 day, 100 MB 등
        retention: "7 days"             # 보관 기간
        compression: "zip"              # 압축 형식
        encoding: "utf-8"
        colorize: false
        serialize: false
        backtrace: true
        diagnose: false
        enqueue: false
        catch: true

# ============================================================================
# ImageOCR - Complete Configuration Example
# ============================================================================
# 모든 가능한 정책 옵션을 포함한 전체 예제입니다.
# 실제 사용시에는 필요한 항목만 선택하여 사용하세요.

ocr:
  # --------------------------------------------------------------------------
  # 2. Provider - OCR 제공자 설정
  # --------------------------------------------------------------------------
  provider:
    provider: "paddle"                  # OCR 제공자: paddle, tesseract 등
    langs: ["ch", "en"]                 # 언어 코드 목록
    min_conf: 0.5                       # 최소 신뢰도 (0.0-1.0)
    
    # PaddleOCR 전용 설정
    paddle_device: "gpu"                # 디바이스: cpu, gpu
    paddle_use_angle_cls: true          # 각도 분류 사용
    paddle_instance: null               # 캐시된 인스턴스 (내부 사용)
  
  # --------------------------------------------------------------------------
  # 3. Preprocess - OCR 전처리 설정
  # --------------------------------------------------------------------------
  preprocess:
    max_width: null                     # OCR용 최대 너비 (리사이즈)
  
  # --------------------------------------------------------------------------
  # 4. Postprocess - OCR 후처리 설정
  # --------------------------------------------------------------------------
  postprocess:
    strip_special_chars: true           # 특수문자 제거
    filter_alphanumeric: true           # 영숫자만 있는 텍스트 필터링
    deduplicate_iou_threshold: 0.7      # 중복 제거 IoU 임계값
    prefer_lang_order: ["ch", "en"]     # 언어 우선순위
  
  # --------------------------------------------------------------------------
  # 6. Meta - 메타데이터 저장 설정 (OCR 결과 포함)
  # --------------------------------------------------------------------------
  meta:
    save_meta: true                     # OCR 결과 JSON 저장
    directory: ""
    
    name:
      as_type: "file"
      prefix: null
      name: ""
      suffix: "_ocr"                    # OCR 메타 접미사
      tail: null
      extension: ".json"
      delimiter: "_"
      tail_mode: null
      date_format: "%Y-%m-%d"
      counter_width: 2
      auto_expand: true
      tail_suffix: null
      sanitize: true
      case: "keep"
      ensure_unique: false
    
    ops:
      as_type: "file"
      exist:
        must_exist: false
        create_if_missing: true
        overwrite: true
      ext:
        require_ext: false
        default_ext: ".json"
        allowed_exts: null
  
  # --------------------------------------------------------------------------
  # 7. Log - 로그 설정
  # --------------------------------------------------------------------------
  log:
    level: "INFO"
    format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"
    colorize: true
    serialize: false
    backtrace: false
    diagnose: false
    enqueue: false
    catch: true
    
    handlers:
      - sink: "${output_xloto_logs_dir}/image_ocr_{time:YYYY-MM-DD}.log"
        level: "DEBUG"
        format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {message}"
        rotation: "1 day"
        retention: "7 days"
        compression: "zip"
        encoding: "utf-8"
        colorize: false
        serialize: false
        backtrace: true
        diagnose: false
        enqueue: false
        catch: true

# ============================================================================
# ImageOverlay - Complete Configuration Example
# ============================================================================
# 모든 가능한 정책 옵션을 포함한 전체 예제입니다.
# 실제 사용시에는 필요한 항목만 선택하여 사용하세요.

overlay:
  # --------------------------------------------------------------------------
  # 2. Texts - 텍스트 오버레이 목록
  # --------------------------------------------------------------------------
  texts:
      # 폰트 설정 (FontPolicy 필드만)
      font:
        family: "NanumGothic"           # 폰트 패밀리 또는 경로 (None = Pillow 기본)
        size: 24                        # 폰트 크기 (픽셀 단위, None = auto-fit)
        fill: "#FFFFFF"                 # 텍스트 색상 (hex)
        stroke_fill: "#000000"          # 외곽선 색상 (None = 외곽선 없음)
        stroke_width: 2                 # 외곽선 두께 (픽셀)
      
      # 텍스트 배치 설정
      anchor: "mm"                      # PIL 앵커: mm(중앙), lt(왼쪽상단) 등
      offset: [0.0, 0.0]                # 위치 오프셋 [dx, dy]
      max_width_ratio: 0.95             # bbox 내 최대 텍스트 너비 비율
  
  # --------------------------------------------------------------------------
  # 3. Background Opacity - 배경 투명도
  # --------------------------------------------------------------------------
  background_opacity: 0.0               # 전체 배경 투명도 (0.0-1.0)
  
  # --------------------------------------------------------------------------
  # 4. Save - 이미지 저장 설정 (FSO 기반)
  # --------------------------------------------------------------------------
  save:
    save_copy: true                     # 오버레이된 이미지 저장
    directory: ""
    
    name:
      as_type: "file"
      prefix: null
      name: ""
      suffix: "_translated"
      tail: null
      extension: null
      delimiter: "_"
      tail_mode: "counter"
      date_format: "%Y-%m-%d"
      counter_width: 3
      auto_expand: true
      tail_suffix: null
      sanitize: true
      case: "keep"
      ensure_unique: true
    
    ops:
      as_type: "file"
      exist:
        must_exist: false
        create_if_missing: true
        overwrite: false
      ext:
        require_ext: false
        default_ext: null
        allowed_exts: null
    
    format: null
    quality: 95
  
  # --------------------------------------------------------------------------
  # 6. Log - 로그 설정
  # --------------------------------------------------------------------------
  log:
    level: "INFO"
    format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"
    colorize: true
    serialize: false
    backtrace: false
    diagnose: false
    enqueue: false
    catch: true
    
    handlers:
      - sink: "${output_xloto_logs_dir}/image_overlay_{time:YYYY-MM-DD}.log"
        level: "DEBUG"
        format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {message}"
        rotation: "1 day"
        retention: "7 days"
        compression: "zip"
        encoding: "utf-8"
        colorize: false
        serialize: false
        backtrace: true
        diagnose: false
        enqueue: false
        catch: true
